### ISSUE TITLE
[US] : Gérer son compte adhérent

### ISSUE THREAD

**Issue by Ozouka** [Munozmu/sae-s6-bibliotheque#3]
- En tant qu’adhérent je peux gérer mon compte

Créer une page dans laquelle on peut voir les infos de l’adhérent (idAdh, dateAdhesion, nom, prenom, dateNaiss, email, adressePostale, numTel, photo) 

Permettre à l’adhérent de modifier certaines informations comme l’email, le numTel…

**Comment by Munozmu** [comment]
route : 
/account

composant :
user-account

Contenu  : 
nom prénom adresse mail adresse (tout doit être modifiable)
les réservations en cours (card de livre)
les réservations passées (si possible avec le back)

**Comment by Munozmu** [comment]
@Ozouka
